// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbqBVV-OE7W65RHJp349FSIf89cooG2c',
    appId: '1:972448197292:web:22dd8b7c234f5e1e214d09',
    messagingSenderId: '972448197292',
    projectId: 'project-emailpassword',
    authDomain: 'project-emailpassword.firebaseapp.com',
    storageBucket: 'project-emailpassword.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7Lhj2VsK986Db__Ss3aPhXQ7EhYjksPA',
    appId: '1:972448197292:android:da84dda497d26c48214d09',
    messagingSenderId: '972448197292',
    projectId: 'project-emailpassword',
    storageBucket: 'project-emailpassword.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf5wXsyD_cZqAAb4GhkVK5FlUjrV3QFYE',
    appId: '1:972448197292:ios:38513e3a12cd4e2f214d09',
    messagingSenderId: '972448197292',
    projectId: 'project-emailpassword',
    storageBucket: 'project-emailpassword.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf5wXsyD_cZqAAb4GhkVK5FlUjrV3QFYE',
    appId: '1:972448197292:ios:38513e3a12cd4e2f214d09',
    messagingSenderId: '972448197292',
    projectId: 'project-emailpassword',
    storageBucket: 'project-emailpassword.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmbqBVV-OE7W65RHJp349FSIf89cooG2c',
    appId: '1:972448197292:web:4619c017476e9670214d09',
    messagingSenderId: '972448197292',
    projectId: 'project-emailpassword',
    authDomain: 'project-emailpassword.firebaseapp.com',
    storageBucket: 'project-emailpassword.firebasestorage.app',
  );
}
